all: user-guide install-guide

user-guide:
	markdown user-guide.md > user-guide.html 

install-guide:
	markdown install-guide.md > install-guide.html

clean:
	rm -f user-guide.html
	rm -f install-guide.html
